site_name: PubSub Services
#site_url: https://pages.github.ford.com/serverless/serverless-hub/
site_description: Project documentation with Markdown.
site_author:  lsamue16@FOPRD.COM
#repo_name: serverless/serverless-hub
#repo_url: https://github.ford.com/serverless/serverless-hub/
#edit_uri: blob/master/docs
copyright: Copyright &copy; 2023 Ford Cloud Platform All Rights Reserved
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - footnotes
  - md_in_html
  - tables
  
# Configuration
theme:
  logo: img/ford-logo.png
  name: material
  features:
    # - navigation.sections
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.indexes
    - navigation.top
    - content.action.edit
    - content.action.view
    - search.highlight
    - search.share
    - search.suggest
  icon:
    edit: material/pencil
    view: material/eye
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
      
    
  language: en
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: indigo
      accent: purple 
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime 
  font:
    text: Roboto
    code: Roboto Mono 

nav:
  - Home: 
########## Left pane navigation ##########
    - PubSub:
      - Overview: pubsub/Overview.md
      - Terraform Modules: https://github.ford.com/gcp/tfm-pubsub
      - Monitoring: pubsub/pubsub-monitoring.md
      - Public Internet Access: pubsub/public-access-pubsub-service.md
      - MultiRegion: pubsub/pubsub-multiregion.md
      - Day 2 Operations: pubsub/pubsub-day2-operations.md
      - Frequently Asked Question (FAQ): pubsub/FAQ.md
####################
  # - Understanding the basics: To-be-defined.md
  # - Core Concepts: Core-concepts.md   
  # - Getting Started:
  - PubSub: 
    # - Introduction:
    #   - What is Cloud Function: Serverless-Docs/cloud-functions/What-is-Cloud-Function.md
    #   - When to use Cloud Function: Serverless-Docs/cloud-functions/When-to-use-Cloud-Function.md
    - Overview: pubsub/Overview.md
    - Terraform Modules: https://github.ford.com/gcp/tfm-pubsub
    - Monitoring: pubsub/pubsub-monitoring.md
    - Public Internet Access: pubsub/public-access-pubsub-service.md
    - MultiRegion: pubsub/pubsub-multiregion.md
    - Day 2 Operations: pubsub/pubsub-day2-operations.md
    - Migrate from 1.0 to 2.0: pubsub/pubsub-migration-2_0.md
    - Frequently Asked Question (FAQ): pubsub/FAQ.md

extra_css:
  - stylesheets/extra.css    
